- name: installing open-vm-tools
  package: name=open-vm-tools state=present
  when: ansible_virtualization_type == "virtualbox"
  become: true

- name: centos | starting and enabling open-vm-tools
  service: name=vmtoolsd.service state=restarted enabled=yes
  when: ansible_os_family == "RedHat" and ansible_virtualization_type == "virtualbox"
  become: true

- name: debian-ubuntu | starting and enabling open-vm-tools
  service: name=open-vm-tools.service state=restarted enabled=yes
  when: ansible_os_family == "Debian" and ansible_virtualization_type == "virtualbox"
  become: true 
