- name: installing open-vm-tools
  package: name=open-vm-tools state=present
  when: ansible_virtualization_type == "virtualbox"
  become: true

- name: load os dependent variables 
  include_vars: "{{ item }}" 
  with_first_found:
       - os_{{ ansible_facts['os_family'] }}.yml
       - os_default.yml
 
- name: start and enable {{ vmtools_service_name }} service 
  service: name={{ vmtools_service_name }} state=restarted enabled=yes
  become: true
  when: ansible_virtualization_type == "virtualbox"
 
