# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
UBUNTU_IMAGE = "ubuntu/xenial64"
CENTOS_IMAGE = "centos/7"
DEBIAN_IMAGE = "debian/jessie64"

Vagrant.configure("2") do |config|
    config.vm.define "ansible-master" do |subconfig|
        subconfig.vm.box = UBUNTU_IMAGE
        subconfig.vm.hostname = "ansible-master"
        subconfig.vm.network :private_network, ip: "10.0.0.10"
        subconfig.vm.synced_folder "../ansible", "/opt/ansible"
    end

    (1..3).each do |i|     
        config.vm.define "ubuntu-node#{i}" do |subconfig|
            subconfig.vm.box = UBUNTU_IMAGE 
            subconfig.vm.hostname = "ubuntu-node#{i}"       
            subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"     
        end
    end

    (1..3).each do |i|     
        config.vm.define "centos-node#{i}" do |subconfig|
            subconfig.vm.box = CENTOS_IMAGE
            subconfig.vm.hostname = "centos-node#{i}"       
            subconfig.vm.network :private_network, ip: "10.0.0.#{i + 20}"     
        end
    end

    (1..3).each do |i|     
        config.vm.define "debian-node#{i}" do |subconfig|
            subconfig.vm.box = DEBIAN_IMAGE
            subconfig.vm.hostname = "debian-node#{i}"       
            subconfig.vm.network :private_network, ip: "10.0.0.#{i + 30}"     
        end
    end
end
